---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false
  vars:
    choco_packages:
      - name: firefox
        version: 97
      
  tasks:
  - name: Install specific versions of packages sequentially
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    
  - name: Check python version
    win_command: firefox --version
    register: check_python_version

  - name: Check nodejs version
    win_command: node --version
    register: check_node_version

  - debug:
      msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}
