---
- name: Install Specific versions of packages using Chocolatey
  hosts: windows
  gather_facts: false
  
  tasks:
  - name: Install specific versions of packages sequentially
    win_chocolatey:
      name: "{{ name }}"
      version: "{{ version }}"   
