---
- name: add users to server 
  hosts: windows
  gather_facts: false
  tasks:
    - name: add user
      win_user:
        name: "{{ user_name }}" 
        password: "{{ user_password }}"
        state: "{{ user_state }}"  
