---
- name: configure VLANs
  hosts: arista
  gather_facts: false
  tasks:
  - name: use vlans resource module
    arista.eos.vlans:
      state: merged
      config:
        - name: desktops
          vlan_id: 23
        - name: servers
          vlan_id: 30
        - name: printers
          vlan_id: 45
        - name: DMZ
          vlan_id: 51
