---
- name: Merge provided configuration with device configuration
  hosts: cisco
  gather_facts: false
  tasks:
    - name: create vlans
      cisco.ios.ios_vlans:
        config:
        - name: test
          vlan_id: 20
          state: active
          shutdown: disabled
        state: merged
