---
- name: Add IP to interface
  hosts: "{{ HOSTS | default('cisco') }}"
  gather_facts: false
  tasks:
    - name: Configure interface IP
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ switch_port }}"
          ipv4:
          - address: "{{ port_ip }}"
        state: merged
