---
- name: Merge provided configuration with device configuration
  hosts: cisco
  gather_facts: false
  tasks:
    - name: create vlans
      cisco.ios.ios_vlans:
        state: merged
        config:
          - name: desktops
            vlan_id: 20
          - name: servers
            vlan_id: 30
          - name: printers
            vlan_id: 40
          - name: DMZ
            vlan_id: 50
