---
- name: Add printer vlan
  hosts: "{{ HOSTS | default('cisco') }}"
  gather_facts: false
  tasks:
    - name: Printer vlans
      cisco.ios.ios_vlans:
        config:
        - name: printer
          vlan_id: 20
          state: active
          shutdown: disabled
        state: merged
