---
- name: Merge provided configuration with device configuration
  hosts: cisco
  gather_facts: false
  tasks:
    - name: create vlans
      ios_vlans:
        config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled
        state: merged
