---
- name: vlans
  hosts: juniper
  gather_facts: false
  tasks:
    - name: create test vlans
      junos_vlans:
        config:
        - name: vlan10
          vlan_id: 10
        - name: vlan20
          vlan_id: 20
        state: merged
