---
- name: vlans
  hosts: juniper
  gather_facts: false
  tasks:
    - name: create test vlans
      junipernetworks.junos.junos_l2_interfaces:
        config:
        - name: gr-0/0/0
          trunk:
            allowed_vlans:
            - DMZ
            - desktops
            - printers
        state: merged
